source theme_files/hwt_config
[ $hwt_theme = default ] && echo "当前选择：MIUI经典"
[ $hwt_theme = coloros12 ] && echo "当前选择：ColorOS12"
[ $hwt_theme = explore ] && echo "当前选择：MIUI探·界 "
[ $hwt_theme = flyme9 ] && echo "当前选择：Flyme9 "
[ $hwt_theme = lrone ] && echo "当前选择：Lrone "
[ $hwt_theme = luck7 ] && echo "当前选择：Luck7 "
[ $hwt_theme = perfectcurve ] && echo "当前选择：完美曲线 "
[ $hwt_theme = Aquamarine ] && echo "当前选择：鸿蒙-润泽"
[ $hwt_theme = AmethystLake ] && echo "当前选择：EMUI-紫晶湖"
[ $hwt_theme = GoldenBeach ] && echo "当前选择：EMUI-碧海金沙"
[ $hwt_theme = LightWings ] && echo "当前选择：EMUI-光之翼"
[ $hwt_theme = Nebulae ] && echo "当前选择：EMUI-宇宙之眼"
[ $hwt_theme = StarrySky ] && echo "当前选择：EMUI-星夜彩绘"
[ $hwt_theme = Reconstruction ] && echo "当前选择：EMUI-未来之翼"